AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AssignmentIndentation:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb

Lint/NestedPercentLiteral:
  Enabled: false

Lint/RedundantRequireStatement:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Metrics/AbcSize:
  Max: 33

Metrics/BlockLength:
  Exclude:
    - 'lib/image_optim/runner/option_parser.rb'
    - 'script/worker_analysis'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 10

Security/MarshalLoad:
  Exclude:
    - 'script/worker_analysis'

Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ArgumentsForwarding:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashConversion:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/OptionalBooleanParameter:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SafeNavigation:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SignalException:
  EnforcedStyle: semantic

Style/SlicingWithRange:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
