name: build-test-containers
on:
  workflow_dispatch:
  schedule:
  - cron: 11 2 13 * *
permissions: {}
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run:
        docker build
          -f Dockerfile.test
          --target ruby-build
          -t ghcr.io/toy/image_optim.test:ruby-build
          --push
          .

  test-images:
    needs: base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - '1.9'
        - '2.0'
        - '2.1'
        - '2.2'
        - '2.3'
        - '2.4'
        - '2.5'
        - '2.6'
        - '2.7'
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
        - '3.4'
        - '4.0'
      fail-fast: false
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run:
        docker build
          -f Dockerfile.test
          --target test
          --build-arg "RUBY_VERSION=${{ matrix.ruby }}"
          -t "ghcr.io/toy/image_optim.test:${{ matrix.ruby }}"
          --push
          .
