name: rubocop
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 2
permissions: {}
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
      with:
        ruby-version: '4'
        bundler-cache: true
    - run: bundle exec rubocop
